Add workaround for meck bug causing test failures
This change works around a meck bug that was producing weird test
failures without any useful error messages. This ultimately turned out
to be triggered by running eunit tests in the riak_kv_stat module prior
to using meck to mock the riak_kv_stat module in the same eunit run. For
info on this bug, see https://github.com/eproxus/meck/issues/133

For reference, this is what the test output looked like:

Pending:
  undefined
    %% Related process exited with reason: killed

Finished in ? seconds
150 tests, 0 failures, 3 cancelled
ERROR: One or more eunit tests failed.